import assert from "node:assert/strict";
import { it, suite } from "node:test";

import { tachyonManifold } from "./lib.ts";

suite("tachyonManifold", () => {
  const input = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`;

  it("calculates beam splits", () => {
    assert.strictEqual(tachyonManifold(input), 21);
  });

  it("calculates quantum states", () => {
    assert.strictEqual(tachyonManifold(input, true), 40);
  });
});
